import {chromium} from 'playwright';import {mkdir} from 'node:fs/promises';await mkdir('test-results',{recursive:true});import assert from 'node:assert/strict';import {writeFile} from 'node:fs/promises';
import {writeArrayBuffer} from 'geotiff';
const browser=await chromium.launch({headless:true,channel:process.platform==='win32'?'msedge':undefined});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[],passed=[];page.on('pageerror',e=>errors.push(e.message));const pass=s=>{passed.push(s);console.log('PASS',s);};
const ready=async()=>{await page.waitForFunction(()=>!document.querySelector('.cq-progress'));if(await page.getByRole('button',{name:'Start analysis',exact:true}).count()){assert.equal(await page.locator('.cq-results').count(),0);await page.getByRole('button',{name:'Start analysis',exact:true}).click();}await page.locator('.cq-results').waitFor();await page.waitForFunction(()=>!document.querySelector('.cq-progress'));assert.equal(await page.getByRole('alert').count(),0);};
const task=async v=>{await page.locator('.cq-control-row select').selectOption(v);await ready();};
const fixture=reverse=>Buffer.from(writeArrayBuffer(Array.from({length:4},(_,i)=>[1,4,2,(i<2)!==reverse?4:1,(i<2)!==reverse?1:4]).flat(),{width:2,height:2,SamplesPerPixel:[5],PhotometricInterpretation:1,ModelPixelScale:[10,10,0],ModelTiepoint:[0,0,0,500000,3200000,0],ProjectedCSTypeGeoKey:32643,GTModelTypeGeoKey:1}));
const upload=async key=>page.getByLabel('Upload '+key,{exact:true}).setInputFiles({name:key+'.tif',mimeType:'image/tiff',buffer:fixture(key==='B')});
const mapping=async key=>{await page.getByText(key==='a'?'T1 / Image A · metadata & bands':'T2 · metadata & bands',{exact:true}).click();const section=page.locator('.cq-metadata').filter({has:page.getByLabel(key+' nir band')});await section.getByText('Advanced: input category and band mapping',{exact:true}).click();await page.getByLabel(key+' nir band').selectOption('3');await page.getByLabel(key+' swir band').selectOption('4');};
try{
await page.goto('http://127.0.0.1:5173/workspace');await upload('A');await ready();assert.deepEqual(await page.locator('.cq-control-row option').evaluateAll(es=>es.map(e=>e.value)),['statistics']);pass('Unlabelled multispectral upload shows statistics after Start without band guessing');await mapping('a');
for(const [t,name] of [['vegetation','NDVI'],['water','NDWI'],['builtup','NDBI']]){await task(t);assert.match(await page.locator('.cq-result-summary').innerText(),/50%/);assert.match(await page.locator('.cq-results').innerText(),new RegExp(name));}pass('Mapped NDVI, NDWI and NDBI each measure expected 50%');
await page.getByRole('button',{name:'Bitemporal',exact:true}).click();await upload('B');await ready();await mapping('b');await task('vegetation');assert.match(await page.locator('.cq-result-summary').innerText(),/50% before and 50% after/);await page.getByText('All measurements and method details',{exact:true}).click();assert.match(await page.locator('.cq-results').innerText(),/Spatial loss\s+50%/);assert.match(await page.locator('.cq-results').innerText(),/Spatial gain\s+50%/);pass('Bitemporal spectral loss/gain distinguishes spatial turnover from zero net change');
for(const layer of ['before','after','lost','gained','delta']){await page.getByLabel('Visible layer').selectOption(layer);assert.equal(await page.locator('.cq-stage img').count(),2);}pass('Spectral before/after, loss, gain and delta layers');
await page.getByRole('button',{name:'Single image',exact:true}).click();await ready();const section=page.locator('.cq-metadata').filter({has:page.getByLabel('a intensity band')});await page.getByLabel('a input category',{exact:true}).selectOption('sar');await page.getByLabel('a intensity band').selectOption('1');await section.getByLabel('scale',{exact:true}).fill('2');await section.getByLabel('offset',{exact:true}).fill('-10');await task('statistics');assert.match(await page.locator('.cq-result-summary').innerText(),/average value is -2/);pass('SAR calibrated intensity statistics use selected band, scale and offset');
await task('sar');await page.getByText('Adjust sensitivity and cleanup',{exact:true}).click();assert.equal(await page.getByLabel('Analysis threshold').getAttribute('min'),'-2');await page.getByLabel('Analysis threshold').fill('-2');await page.getByRole('button',{name:/^(Start analysis|Run analysis again)$/}).click();await ready();assert.match(await page.locator('.cq-result-summary').innerText(),/0%/);pass('SAR threshold with calibrated negative values');
await section.getByText('Transform and band metadata',{exact:true}).click();assert.match(await section.innerText(),/32643/);await page.getByText('Raw band statistics · T1',{exact:true}).click();assert.equal(await page.locator('.cq-histogram').count(),5);pass('CRS, transform, band metadata and per-band histograms');
for(const ext of ['png','jpeg','webp']){const buffer=Buffer.from(await page.evaluate(ext=>{const c=document.createElement('canvas');c.width=8;c.height=8;c.getContext('2d').fillRect(0,0,8,8);return [...Uint8Array.from(atob(c.toDataURL('image/'+ext).split(',')[1]),x=>x.charCodeAt(0))];},ext));await page.getByLabel('Upload A',{exact:true}).setInputFiles({name:'image.'+ext,mimeType:'image/'+ext,buffer});await ready();}pass('PNG, JPEG and WebP upload → Start flows');
await page.getByLabel('Upload A',{exact:true}).setInputFiles({name:'bad.txt',mimeType:'text/plain',buffer:Buffer.from('bad')});await page.getByRole('alert').waitFor();assert.match(await page.getByRole('alert').innerText(),/Choose TIFF/);pass('Unsupported format rejected without crash');
await page.getByRole('button',{name:/Indus floodplain/}).click();await ready();await page.route('**/api/chat',r=>r.fulfill({json:{answer:'Measured visual change explained.',model:'mock-free',toolCalls:[]}}));await page.getByRole('button',{name:'Explain with free AI',exact:true}).click();await page.getByText('Measured visual change explained.',{exact:true}).waitFor();pass('Preview + Start: explanation dispatches without typing');
await page.getByRole('button',{name:/Delhi–Haryana cropland/}).click();await ready();assert.equal(await page.getByLabel('3×3 noise cleanup').isChecked(),false);await page.getByLabel('Explanation settings').click();await page.getByLabel('Explanation settings').click();await page.reload();await page.getByRole('button',{name:/Delhi–Haryana cropland/}).click();await ready();await page.screenshot({path:'test-results/ux-final-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:'test-results/ux-final-mobile.png',fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);pass('Sample presets reset tuning; fresh desktop/mobile layout');
}finally{await writeFile('test-results/advanced-results.json',JSON.stringify({passed,errors},null,2));await browser.close();}
