import {chromium} from 'playwright';import {mkdir} from 'node:fs/promises';await mkdir('test-results',{recursive:true});
import {writeFile} from 'node:fs/promises';
import {writeArrayBuffer} from 'geotiff';
import assert from 'node:assert/strict';

const browser=await chromium.launch({headless:true,channel:process.platform==='win32'?'msedge':undefined});
const page=await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true});const errors=[],passed=[];
page.on('pageerror',e=>errors.push(e.message));const pass=s=>{passed.push(s);console.log('PASS',s);};
const ready=async()=>{await page.locator('.cq-results').waitFor();await page.getByRole('button',{name:'Recompute',exact:true}).waitFor();assert.equal(await page.getByRole('alert').count(),0);};
const task=async t=>{await page.locator('.cq-control-row select').selectOption(t);await ready();};
const ask=async q=>{await page.getByLabel('Question about imagery').fill(q);await page.getByRole('button',{name:'Ask',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('.cq-chat [role=status]:last-child')&&![...document.querySelectorAll('.cq-chat p')].some(x=>x.textContent==='Reading the evidence…'),{},{timeout:110000});};
const tif=(values,bands=1,crs=32643,width=2)=>Buffer.from(writeArrayBuffer(values,{width,height:values.length/(width*bands),SamplesPerPixel:[bands],PhotometricInterpretation:bands===3?2:1,ModelPixelScale:[10,10,0],ModelTiepoint:[0,0,0,500000,3200000,0],ProjectedCSTypeGeoKey:crs,GTModelTypeGeoKey:1}));
const upload=async(key,buffer,name='fixture.tif')=>{await page.getByLabel('Upload '+key,{exact:true}).setInputFiles({name,mimeType:'image/tiff',buffer});};
try{
await page.goto('http://127.0.0.1:5173/workspace');await page.locator('.cq-model option[value=nemotron]').waitFor({state:'attached'});
for(const name of ['Indus floodplain','Delhi–Haryana cropland','Delhi urban expansion']){
 await page.getByRole('button',{name:new RegExp(name)}).click();await ready();assert.equal(await page.getByLabel('Confirm image alignment').count(),0);
 const options=await page.locator('.cq-control-row option').evaluateAll(es=>es.map(e=>e.value));
 assert.deepEqual(options,name.includes('cropland')?['statistics','vegetation']:['statistics','change']);
 pass('One-click '+name+' with automatic results and supported tasks only');
}
await page.getByLabel('Visible layer').selectOption('compare');await page.getByLabel('Before after comparison').fill('25');assert.match(await page.locator('.cq-stage img').nth(1).getAttribute('style'),/75%/);pass('Comparison slider');
for(const layer of ['t1','t2','side','mask','overlay','delta']){await page.getByLabel('Visible layer').selectOption(layer);assert.ok(await page.locator('.cq-stage img').count());}pass('Original, after, side-by-side, mask, overlay and signed-difference layers');
await page.getByLabel('Visible layer').selectOption('overlay');await page.getByLabel('Overlay opacity').fill('30');assert.equal(await page.locator('.cq-stage img').last().evaluate(e=>e.style.opacity),'0.3');pass('Opacity changes display');
await page.getByLabel('Zoom in',{exact:true}).click();assert.match(await page.locator('.cq-stage').getAttribute('style'),/1.25/);const box=await page.locator('.cq-viewer').boundingBox();await page.mouse.move(box.x+100,box.y+100);await page.mouse.down();await page.mouse.move(box.x+140,box.y+130);await page.mouse.up();assert.match(await page.locator('.cq-stage').getAttribute('style'),/40px/);await page.getByLabel('Reset viewer').click();assert.match(await page.locator('.cq-stage').getAttribute('style'),/scale\(1\)/);pass('Zoom, pan and reset');
await page.getByText('Adjust sensitivity and cleanup',{exact:true}).click();await page.getByLabel('Analysis threshold').fill('255');assert.equal(await page.locator('.cq-results').count(),0);await page.getByRole('button',{name:'Recompute',exact:true}).click();await ready();assert.match(await page.locator('.cq-result-summary').innerText(),/^0%/);await page.getByLabel('3×3 noise cleanup').check();await page.getByRole('button',{name:'Recompute',exact:true}).click();await ready();pass('Threshold invalidation, recompute and morphology');
const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Export evidence'}).click();const download=await downloadPromise;const stream=await download.createReadStream();let json='';for await(const chunk of stream)json+=chunk;const exported=JSON.parse(json);assert.equal(exported.analysis.threshold,255);assert.equal(exported.analysis.morphology,true);pass('JSON export contains actual selected settings');
await page.getByRole('button',{name:'Single image',exact:true}).click();await ready();assert.equal(await page.getByLabel('Upload B').count(),0);pass('Switching modes recalculates correctly');
const rgb=Buffer.from(await page.evaluate(()=>{const c=document.createElement('canvas');c.width=16;c.height=16;const x=c.getContext('2d');x.fillStyle='rgb(20,180,20)';x.fillRect(0,0,8,16);x.fillStyle='rgb(20,30,200)';x.fillRect(8,0,8,16);return [...Uint8Array.from(atob(c.toDataURL().split(',')[1]),v=>v.charCodeAt(0))];}));
await upload('A',rgb,'test.png');await ready();for(const t of ['vegetation','water','builtup','statistics']){await task(t);assert.match(await page.locator('.cq-results').innerText(),t==='statistics'?/Mean value/:/RGB/);}pass('PNG upload automatically analyses; all RGB tasks run');
await upload('A',tif([10,20,30,40]));await ready();assert.match(await page.locator('.cq-result-summary').innerText(),/25/);console.log('RGB OPTION',await page.locator('.cq-view-options option[value=rgb]').evaluate(e=>e.outerHTML));assert.equal(await page.locator('.cq-view-options option[value=rgb]').evaluate(e=>e.disabled),true);pass('Single-band GeoTIFF auto statistics, metadata and honest grayscale');
await page.getByRole('button',{name:'Bitemporal',exact:true}).click();await upload('B',tif([10,20,70,80]));await ready();await page.getByLabel('3×3 noise cleanup').uncheck();await page.getByRole('button',{name:'Recompute',exact:true}).click();await ready();assert.match(await page.locator('.cq-result-summary').innerText(),/^50%/);pass('Uploaded aligned GeoTIFF pair auto comparison, known 50% difference');
await upload('B',tif([10,20,70,80],1,4326));await page.getByRole('alert').waitFor();assert.match(await page.getByRole('alert').innerText(),/CRS/);assert.equal(await page.locator('.cq-results').count(),0);pass('Incompatible CRS safely rejected with no stale result');
await upload('B',Buffer.from('bad'),'corrupt.tif');await page.getByRole('alert').waitFor();pass('Corrupt TIFF handled without page crash');
await page.getByRole('button',{name:/Delhi–Haryana cropland/}).click();await ready();assert.match(await page.locator('.cq-results').innerText(),/NDVI/);await page.locator('.cq-model select').selectOption('local');await ask('Explain this result.');assert.match(await page.locator('[data-testid=request-status]').innerText(),/no AI request/);pass('Recovery after invalid upload and explicit local summary');
await page.locator('.cq-model select').selectOption('nemotron');let captured;
await page.route('**/api/chat',r=>{captured=r.request().postDataJSON();return r.fulfill({json:{answer:'Test explanation from measured evidence.',model:'mock-free',toolCalls:['get_analysis_summary']}});});await ask('Explain this result.');assert.equal(captured.context.analysis.task,'vegetation');assert.match(await page.locator('[data-testid=request-status]').innerText(),/AI response received/);pass('External chat dispatch and response rendering (mock provider)');
await page.unroute('**/api/chat');await page.route('**/api/chat',r=>r.fulfill({status:429,json:{detail:'Free quota reached'}}));await ask('Explain this result.');assert.match(await page.locator('[data-testid=request-status]').innerText(),/Free quota/);assert.equal(await page.locator('.cq-results').count(),1);pass('Quota error preserves measurements');
await page.unroute('**/api/chat');await page.route('**/api/models',r=>r.fulfill({status:503,body:'offline'}));await page.getByRole('button',{name:'Retry connection'}).click();await page.getByText(/AI gateway offline/).first().waitFor();await page.unroute('**/api/models');await page.getByRole('button',{name:'Retry connection'}).click();await page.getByText(/Gateway connected/).first().waitFor();pass('Gateway failure and retry recovery');
await page.getByLabel('Explanation settings').click();assert.match(await page.locator('.cq-notice').innerText(),/Paid fallback/);pass('Provider settings and privacy information');
await page.screenshot({path:'test-results/ux-desktop.png',fullPage:true});
await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:/Indus floodplain/}).click();await ready();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'test-results/ux-mobile.png',fullPage:true});pass('Mobile one-click demo without horizontal overflow');
await page.locator('.cq-brand').click();await page.waitForURL('http://127.0.0.1:5173/');assert.ok(await page.locator('h1').count());pass('Return to unchanged landing page');assert.deepEqual(errors,[]);pass('No uncaught browser exceptions');
}finally{await writeFile('test-results/ux-results.json',JSON.stringify({passed,errors},null,2));await browser.close();}

