import React, { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowLeft, ArrowRight, Upload, Layers, MessageSquare, Settings, Download, Plus, Minus, RotateCcw, Crosshair, LoaderCircle } from 'lucide-react';
import { Client, decodeRgb } from './client';
import { defaultMapping, statistics } from './engine';
import { inferMapping, renderRaster } from './raster';
import scenes from '../scenes.json';
import './workspace.css';

const taskNames={statistics:'Image statistics',vegetation:'Vegetation',water:'Water',builtup:'Built-up areas',change:'Visual / intensity change',sar:'SAR intensity threshold'};
const format=v=>v===null||v===undefined?'Unavailable':typeof v==='number'?Number(v.toFixed(3)).toLocaleString():String(v);
function dataUrl(values,width,height){const c=document.createElement('canvas');c.width=width;c.height=height;c.getContext('2d').putImageData(new ImageData(values,width,height),0,0);return c.toDataURL();}
function maskUrl(values,width,height,color=[183,245,104]){const rgba=new Uint8ClampedArray(width*height*4);values?.forEach((v,i)=>{if(v){rgba.set(color,i*4);rgba[i*4+3]=255;}});return dataUrl(rgba,width,height);}
function explain(question,context){
 const q=question.toLowerCase(),s=context.analysis,m=context.metadata;
 if(/\b(crs|resolution|bands?|metadata|bounds)\b/.test(q)&&!/(vegetation|water|lost|loss|change)/.test(q))return m.length?m.map(x=>`${x.filename}: ${x.width} × ${x.height}, ${x.bands} bands. CRS: ${x.crs||'unavailable'}. Resolution: ${x.resolution?.join(' × ')||'unavailable'} ${x.units}.`).join('\n'):'Upload an image to inspect its metadata.';
 if(/what.*(ndvi|ndwi|ndbi)|mean.*(ndvi|ndwi|ndbi)|define/.test(q))return 'NDVI compares NIR and Red for vegetation; NDWI compares Green and NIR for water; NDBI compares SWIR and NIR for built-up screening. These indices require correctly mapped, calibrated bands. A threshold selects pixels; it is not a confidence score.';
 if(!s)return 'Upload imagery and run an analysis first. I can explain measured coverage, metadata and temporal differences; I cannot infer objects from the image.';
 if(/what.*(show|image)|describe/.test(q))return `Available evidence is ${s.method}. This prototype has no scene-captioning or object-recognition model. ${s.totalPixels.toLocaleString()} valid grid pixels were analysed; use the layers to inspect spatial evidence.`;
 if(s.netPercentagePoints!==null)return `${taskNames[s.task]} coverage: ${format(s.beforeCoverage)}% before → ${format(s.afterCoverage)}% after. Net change: ${format(s.netPercentagePoints)} percentage points. Spatial loss: ${format(s.lostCoverage)}%; gain: ${format(s.gainedCoverage)}% of the common valid area. Method: ${s.method}. This does not establish why the change occurred.`;
 if(s.coverage!==null)return `${format(s.coverage)}% (${s.detectedPixels.toLocaleString()} of ${s.totalPixels.toLocaleString()} valid pixels) passes the selected rule. Method: ${s.method}; threshold ${s.threshold}. ${s.largestQuadrant?'The largest concentration is in the '+s.largestQuadrant+' of the image.':''} ${s.task==='change'?'This is general visual/intensity change, not a land-cover-specific loss estimate.':''}`;
 return `${s.method}: minimum ${format(s.statisticsAfter.min)}, maximum ${format(s.statisticsAfter.max)}, mean ${format(s.statisticsAfter.mean)}, standard deviation ${format(s.statisticsAfter.std)} across ${s.statisticsAfter.count.toLocaleString()} valid pixels. Statistics use the reduced analysis grid.`;
}
function inferTask(question){const q=question.toLowerCase();if(/what.*mean|define|\b(crs|resolution|metadata|band information)\b/.test(q))return null;if(/vegetation|forest|crop|ndvi/.test(q))return 'vegetation';if(/water|flood|ndwi/.test(q))return 'water';if(/built|building|urban|ndbi/.test(q))return 'builtup';if(/sar|intensity/.test(q))return 'sar';if(/change|difference|before|after/.test(q))return 'change';return null;}

export default function ConstrainedWorkspace({onHome}){
 const [mode,setMode]=useState('single'),[data,setData]=useState({a:null,b:null}),[maps,setMaps]=useState({a:{...defaultMapping},b:{...defaultMapping}});
 const [task,setTask]=useState('statistics'),[threshold,setThreshold]=useState(20),[morphology,setMorphology]=useState(false),[accepted,setAccepted]=useState(false);
 const [result,setResult]=useState(null),[busy,setBusy]=useState(''),[error,setError]=useState(''),[layer,setLayer]=useState('t1'),[opacity,setOpacity]=useState(.55),[split,setSplit]=useState(50);
 const [provider,setProvider]=useState('local'),[models,setModels]=useState([]),[settingsOpen,setSettingsOpen]=useState(false),[question,setQuestion]=useState(''),[messages,setMessages]=useState([]),[chatBusy,setChatBusy]=useState(false);
 const [display,setDisplay]=useState('rgb'),[displayBand,setDisplayBand]=useState(0),[zoom,setZoom]=useState(1),[pan,setPan]=useState({x:0,y:0});
 const client=useRef(null),generation=useRef(0),drag=useRef(null),conversation=useRef(0);
 useEffect(()=>{client.current=new Client();return()=>{generation.current++;client.current.cancel();};},[]);
 useEffect(()=>{fetch('/api/models').then(r=>r.ok?r.json():[]).then(setModels).catch(()=>setModels([]));},[]);
 const current=mode==='bitemporal'?data.b||data.a:data.a;
 function invalidate(){generation.current++;conversation.current++;setResult(null);setMessages([]);setError('');setLayer('t1');setZoom(1);setPan({x:0,y:0});}
 function updateMode(value){invalidate();setMode(value);if(value==='single'&&task==='change')setTask('statistics');}
 function defaultThreshold(next,m=maps.a){return next==='change'?30:next==='vegetation'?m.category==='multispectral'?.55:20:next==='water'?m.category==='multispectral'?0:1:next==='builtup'?m.category==='multispectral'?0:.81:0;}
 function chooseTask(value){invalidate();setTask(value);setThreshold(defaultThreshold(value));}
 async function upload(file,key){if(!file)return;invalidate();const token=++generation.current;setBusy('Decoding '+file.name);try{
  if(!/\.(tiff?|png|jpe?g|webp)$/i.test(file.name))throw new Error('Choose TIFF, GeoTIFF, PNG, JPG or WebP.');
  const decoded=/\.tiff?$/i.test(file.name)?await client.current.request({action:'decode',file}):await decodeRgb(file);
  if(token!==generation.current)return;
  setData(old=>({...old,[key]:decoded}));const mapping=inferMapping(decoded);setMaps(old=>({...old,[key]:mapping}));setTask('statistics');setThreshold(0);setAccepted(false);
 }catch(e){if(token===generation.current)setError(e.message);}finally{setBusy('');}}
 async function sample(id){invalidate();const token=++generation.current;setBusy('Loading real sample imagery');try{
  const scene=scenes.find(s=>s.id===id);
  const read=async name=>{const r=await fetch(`/scenes/${name}.webp`);if(!r.ok)throw new Error('Sample image unavailable');return decodeRgb(new File([await r.blob()],name+'.webp'));};
  let a=await read(scene.a),b=scene.b?await read(scene.b):null,ma=inferMapping(a);
  if(scene.spectral){const cfg=scene.spectral;const arrays=await Promise.all([cfg.red,cfg.nir,cfg.classification].map(async url=>{const r=await fetch(url);if(!r.ok)throw new Error('Sample band unavailable');return r.arrayBuffer();}));const valid=Uint8Array.from(new Uint8Array(arrays[2]),v=>cfg.invalidClasses.includes(v)?0:1);
   a={...a,width:cfg.width,height:cfg.height,bands:[Float32Array.from(new Uint16Array(arrays[0])),Float32Array.from(new Uint16Array(arrays[1]))],valid,metadata:{...a.metadata,width:scene.spatial.sourceWidth,height:scene.spatial.sourceHeight,bands:2,dataType:'uint16',category:'multispectral',resolution:[10,-10],units:'metres',bandInfo:[{DESCRIPTION:'red'},{DESCRIPTION:'nir'}],source:scene.source}};
   const meta=await fetch('/scenes/delhi-s2-metadata.json').then(r=>r.json());a.metadata.crs=meta.crs||'EPSG:32643';a.metadata.bounds=meta.bboxProjected||meta.bboxUtm43N||null;a.metadata.transform=a.metadata.bounds?[10,0,a.metadata.bounds[0],0,-10,a.metadata.bounds[3]]:null;
   ma={...defaultMapping,category:'multispectral',red:0,green:-1,blue:-1,nir:1,scale:cfg.scale,offset:cfg.offset};setDisplay('band');
  }else {setDisplay('rgb');if(/false color/i.test(scene.sensor)){a.metadata.category='unknown';ma.category='unknown';if(b)b.metadata.category='unknown';a.metadata.source=scene.source;}}
  if(token!==generation.current)return;setData({a,b});setMaps({a:ma,b:b?inferMapping(b):{...defaultMapping}});setMode(b?'bitemporal':'single');setAccepted(false);setTask(scene.spectral?'vegetation':'statistics');setThreshold(scene.spectral?.55:0);
 }catch(e){setError(e.message);}finally{setBusy('');}}
 const context=(analysis=result?.summary)=>({mode,metadata:[data.a,...(mode==='bitemporal'?[data.b]:[])].filter(Boolean).map(d=>d.metadata),bandMappings:mode==='bitemporal'?maps:{a:maps.a},analysis:analysis||null,layers:analysis?['T1',...(mode==='bitemporal'?['T2','comparison','change/loss/gain']:[]),'mask']:['original']});
 async function run(nextTask=task,nextThreshold=threshold){
  if(!data.a)throw new Error('Upload Image A first.');if(mode==='bitemporal'&&!data.b)throw new Error('Bitemporal analysis needs Image T2.');
  const token=generation.current;setBusy('Computing masks and statistics');try{const value=await client.current.request({action:'analyze',a:data.a,b:mode==='bitemporal'?data.b:null,options:{task:nextTask,threshold:nextThreshold,morphology,acceptUnreferenced:accepted,mappingA:maps.a,mappingB:maps.b}});if(token!==generation.current)throw new Error('Inputs changed; run the analysis again.');setResult(value);setLayer(value.mask?'overlay':'t1');setError('');return value;}finally{setBusy('');}
 }
 async function submit(e){e.preventDefault();if(!question.trim()||chatBusy||busy)return;const q=question.trim(),version=conversation.current;setQuestion('');setChatBusy(true);setMessages(old=>[...old,{role:'user',content:q}]);try{
  const inferred=inferTask(q);let analysis=result?.summary;
  if(inferred&&/change|decreas|increas|loss|lost|gain|before|after/i.test(q)&&(mode!=='bitemporal'||!data.b))throw new Error('This question needs two aligned images. Select Bitemporal mode and upload T1 and T2 first.');
  if(inferred){const nextThreshold=inferred===task?threshold:defaultThreshold(inferred);setTask(inferred);setThreshold(nextThreshold);analysis=(await run(inferred,nextThreshold)).summary;}
  const evidence=context(analysis);let answer,trace;
  if(provider==='local'){answer=explain(q,evidence);trace='Local evidence explanation · no LLM';}
  else {const response=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({provider,question:q,context:evidence,history:messages.slice(-6).map(({role,content})=>({role,content}))}),signal:AbortSignal.timeout(150000)});const body=await response.json();if(!response.ok)throw new Error(body.detail||'Chat gateway unavailable');answer=body.answer;trace=`${body.model} · tools: ${body.toolCalls.join(', ')||'provided evidence'}`;}
  if(version===conversation.current)setMessages(old=>[...old,{role:'assistant',content:answer,trace}]);
 }catch(e){if(version===conversation.current)setMessages(old=>[...old,{role:'assistant',content:e.message,trace:'Request failed — no model answer generated'}]);}finally{setChatBusy(false);}}
 const previews=useMemo(()=>{const out={};for(const key of ['a','b'])if(data[key]){try{out[key]=dataUrl(renderRaster(data[key],maps[key],display,Math.min(displayBand,data[key].bands.length-1)),data[key].width,data[key].height);}catch{out[key]=dataUrl(renderRaster(data[key],maps[key],'band',0),data[key].width,data[key].height);}}return out;},[data,maps,display,displayBand]);
 const masks=useMemo(()=>{if(!result||!current)return {};const {width,height}=result.summary.grid,out={binary:maskUrl(result.mask,result.summary.grid.width,result.summary.grid.height,[255,255,255])};for(const key of ['mask','before','after','lost','gained'])out[key]=maskUrl(result[key],width,height,key==='lost'?[255,130,100]:key==='gained'?[87,212,255]:[183,245,104]);if(mode==='bitemporal'){const rgba=new Uint8ClampedArray(width*height*4);let max=0;for(const v of result.difference)if(Number.isFinite(v))max=Math.max(max,Math.abs(v));result.difference.forEach((v,i)=>{if(Number.isFinite(v)){rgba.set(v<0?[255,130,100]:[87,212,255],i*4);rgba[i*4+3]=max?Math.abs(v)/max*255:0;}});out.delta=dataUrl(rgba,width,height);}return out;},[result,current,mode]);
 const numericStats=useMemo(()=>current?current.bands.map(b=>statistics(b,current.valid)):[],[current]);
 function mappingChange(key,field,value){invalidate();setMaps(old=>({...old,[key]:{...old[key],[field]:value}}));setTask('statistics');setThreshold(0);}
 function exportReport(){const blob=new Blob([JSON.stringify(context(),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='satquery-evidence.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 const range=task==='change'?[0,255,1]:maps.a.category==='multispectral'&&['vegetation','water','builtup'].includes(task)?[-1,1,.01]:task==='vegetation'?[-80,160,1]:task==='water'?[0,2,.01]:task==='builtup'?[0,1,.01]:[numericStats[0]?.min||0,numericStats[0]?.max||255,.01];
 return <div className="cq">
  <header className="cq-header"><button onClick={onHome} className="cq-brand"><Crosshair/> SatQuery <b>AI</b></button><div className="cq-modes" aria-label="Processing mode">{['single','bitemporal'].map(v=><button key={v} aria-pressed={mode===v} disabled={!!busy||chatBusy} onClick={()=>updateMode(v)}>{v==='single'?'Single image':'Bitemporal'}</button>)}</div><label className="cq-model">Explanation<select value={provider} onChange={e=>setProvider(e.target.value)}><option value="local">Local evidence summary</option>{['nemotron','glm','gemma'].map((id,i)=><option key={id} value={id} disabled={!models.find(m=>m.id===id)?.configured}>{['Nemotron 3.5 Lite','GLM 5.2','Gemma 4'][i]}{models.find(m=>m.id===id)?.configured?'':' · not configured'}</option>)}</select></label><button aria-label="Explanation settings" onClick={()=>setSettingsOpen(!settingsOpen)}><Settings/></button></header>
  <main className="cq-main"><div className="cq-heading"><div><span>CONSTRAINED REMOTE-SENSING ANALYSIS</span><h1>Evidence first. Explanation second.</h1><p>Inspect your imagery, calculate a result, and ask what it means.</p></div><button className="cq-outline" disabled={!result} onClick={exportReport}><Download size={16}/> Export evidence</button></div>
  {settingsOpen&&<section className="cq-card cq-notice"><h2>Explanation providers</h2><p>Images are processed locally. Selecting an external model sends your question, filename, geospatial metadata and computed statistics to that provider. Raw rasters and masks are not sent. API credentials stay in the gateway.</p><p>{models.some(m=>m.configured)?'Configured models are available in the selector.':'External chat is not configured. Local evidence summaries work without an API.'} Provider profiles require an exact model ID from your chosen API; the PRD names are labels.</p></section>}
  {error&&<div className="cq-error" role="alert">{error}</div>}
  <section className="cq-inputs"><div className="cq-uploads">{(mode==='single'?['a']:['a','b']).map(key=><label key={key} className="cq-upload"><Upload size={18}/><div><strong>{key==='a'?mode==='single'?'Image A':'T1 · Before':'T2 · After'}</strong><span>{data[key]?.metadata.filename||'GeoTIFF, TIFF, PNG, JPG, WebP'}</span></div><input type="file" accept=".tif,.tiff,.png,.jpg,.jpeg,.webp" aria-label={`Upload ${key.toUpperCase()}`} disabled={!!busy||chatBusy} onChange={e=>{upload(e.target.files[0],key);e.target.value='';}}/></label>)}</div><label>Or explore real data<select defaultValue="" disabled={!!busy||chatBusy} onChange={e=>{sample(e.target.value);e.target.value='';}}><option value="" disabled>Select sample…</option>{scenes.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select></label></section>
  <div className="cq-layout"><section className="cq-left">
   <div className="cq-card"><div className="cq-toolbar"><span><Layers size={16}/> Raster viewer</span><select aria-label="Visible layer" value={layer} onChange={e=>setLayer(e.target.value)}><option value="t1">T1 / original</option>{mode==='bitemporal'&&data.b&&<><option value="t2">T2 / after</option><option value="compare">Before / after slider</option><option value="side">Side by side</option></>}{result?.mask&&<><option value="mask">Binary analysis mask</option><option value="overlay">Analysis overlay</option><option value="before">T1 coverage mask</option><option value="after">T2 coverage mask</option>{mode==='bitemporal'&&<><option value="lost">Lost regions (coral)</option><option value="gained">Gained regions (blue)</option><option value="delta">Signed difference (− coral / + blue)</option></>}</>}</select><button aria-label="Zoom out" onClick={()=>setZoom(z=>Math.max(1,z-.25))}><Minus size={15}/></button><button aria-label="Zoom in" onClick={()=>setZoom(z=>Math.min(5,z+.25))}><Plus size={15}/></button><button aria-label="Reset viewer" onClick={()=>{setZoom(1);setPan({x:0,y:0});}}><RotateCcw size={15}/></button></div>
   <div className="cq-viewer" onPointerDown={e=>{if(zoom<=1)return;drag.current={x:e.clientX-pan.x,y:e.clientY-pan.y};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(drag.current)setPan({x:e.clientX-drag.current.x,y:e.clientY-drag.current.y});}} onPointerUp={()=>drag.current=null} onPointerCancel={()=>drag.current=null}>
    {data.a?<div className={`cq-stage ${layer==='side'?'cq-side':''}`} style={{transform:`translate(${pan.x}px,${pan.y}px) scale(${zoom})`,aspectRatio:`${current.width}/${current.height}`}}>{layer==='side'?<><img draggable="false" src={previews.a} alt="Before image"/><img draggable="false" src={previews.b} alt="After image"/></>:layer==='compare'?<><img draggable="false" src={previews.b} alt="After image"/><img draggable="false" src={previews.a} alt="Before image" style={{clipPath:`inset(0 ${100-split}% 0 0)`}}/><div className="cq-splitline" style={{left:split+'%'}}/></>:layer==='mask'?<img src={masks.binary} alt="Binary selected-pixel mask" className="cq-mask"/>:<><img draggable="false" src={layer==='t1'?previews.a:previews.b||previews.a} alt="Source raster"/>{!['t1','t2'].includes(layer)&&<img draggable="false" src={masks[layer==='overlay'?'mask':layer]} alt={layer+' analysis overlay'} style={{opacity}}/>}</>}</div>:<div className="cq-empty"><Crosshair size={40}/><h2>Your raster, ready to inspect.</h2><p>Upload an image or choose a real sample.</p></div>}
   </div><div className="cq-view-options"><label>Display<select value={display} onChange={e=>setDisplay(e.target.value)}><option value="rgb">RGB band composition</option><option value="band">Grayscale band</option></select></label>{display==='band'&&<label>Band<select value={displayBand} onChange={e=>setDisplayBand(Number(e.target.value))}>{current?.bands.map((_,i)=><option key={i} value={i}>Band {i+1}</option>)}</select></label>}<label>{layer==='compare'?'Reveal T1':'Overlay opacity'}<input aria-label={layer==='compare'?'Before after comparison':'Overlay opacity'} type="range" min="0" max="100" value={layer==='compare'?split:opacity*100} onChange={e=>layer==='compare'?setSplit(+e.target.value):setOpacity(+e.target.value/100)}/></label></div><p className="cq-caption">{current?`${current.width} × ${current.height} analysis grid · ${Math.round(zoom*100)}% zoom · drag to pan when zoomed`:'North-up raster viewer'}{current?.metadata.bounds&&` · bounds (${current.metadata.crs}): ${current.metadata.bounds.map(v=>format(v)).join(', ')}`}. GeoTIFF display uses per-band min/max stretch; analytical values are preserved.</p></div>
   <section className="cq-card cq-controls"><h2>Analysis</h2><div className="cq-control-row"><label>Task<select value={task} disabled={!!busy||chatBusy} onChange={e=>chooseTask(e.target.value)}>{Object.entries(taskNames).map(([key,name])=><option key={key} value={key} disabled={key==='change'&&mode!=='bitemporal'}>{name}</option>)}</select></label>{task!=='statistics'&&<label>Threshold: {threshold}<input aria-label="Analysis threshold" type="range" min={range[0]} max={range[1]===range[0]?range[1]+1:range[1]} step={range[2]} value={threshold} disabled={!!busy||chatBusy} onChange={e=>{setThreshold(+e.target.value);invalidate();}}/></label>}<label className="cq-check"><input type="checkbox" checked={morphology} disabled={!!busy||chatBusy} onChange={e=>{setMorphology(e.target.checked);invalidate();}}/>3×3 noise cleanup</label></div>{mode==='bitemporal'&&<label className="cq-check"><input type="checkbox" checked={accepted} onChange={e=>{setAccepted(e.target.checked);invalidate();}}/>For inputs without georeferencing, I confirm both cover the same aligned area.</label>}<button className="cq-primary" disabled={!!busy||chatBusy||!data.a} onClick={()=>run().catch(e=>setError(e.message))}>{busy?<><LoaderCircle className="spin" size={16}/>{busy}</>:<>Run analysis <ArrowRight size={16}/></>}</button><p className="cq-caption">Changing controls invalidates the previous result. Run again to apply. RGB water selects pixels when B exceeds 1.18R, 1.05G and 32 at threshold 1. Higher thresholds are stricter.</p></section>
   {result&&<section className="cq-card cq-results"><h2>{result.summary.method}</h2><div className="cq-metrics">{[['Detected coverage',result.summary.coverage,'%'],['Before',result.summary.beforeCoverage,'%'],['After',result.summary.afterCoverage,'%'],['Net change',result.summary.netPercentagePoints,' pp'],['Spatial loss',result.summary.lostCoverage,'%'],['Spatial gain',result.summary.gainedCoverage,'%'],['Mean difference',result.summary.meanDifference,''],['Area',result.summary.areaM2===null?null:result.summary.areaM2/1e6,' km²']].filter(([,v])=>v!==null).map(([label,value,unit])=><div key={label}><span>{label}</span><strong>{format(value)}{unit}</strong></div>)}</div><p>{format(result.summary.detectedPixels)} selected / {result.summary.totalPixels.toLocaleString()} common valid pixels. {result.summary.unchangedPixels!==null&&`${result.summary.unchangedPixels.toLocaleString()} unselected pixels.`}</p>{result.summary.ndviClasses&&<p>Unfiltered index classes — NDVI low vegetation (0.2–0.55): {format(result.summary.ndviClasses.after.lowCoverage)}%. High vegetation (&gt;0.55): {format(result.summary.ndviClasses.after.highCoverage)}%.</p>}<p className="cq-caption">{result.summary.confidence}</p>{result.summary.warnings.map(w=><p className="cq-warning" key={w}>{w}</p>)}<details><summary>Auditable execution summary</summary><pre>{JSON.stringify({task:result.summary.task,method:result.summary.method,threshold,morphology,grid:result.summary.grid,bandMappings:maps,steps:['Input metadata validation','Band selection and nodata exclusion','Deterministic calculation','Optional morphology','Common-valid-grid quantification']},null,2)}</pre></details></section>}
  </section><aside className="cq-right"><section className="cq-card cq-chat"><h2><MessageSquare size={18}/> Ask the evidence</h2><p className="cq-caption">{provider==='local'?'Local deterministic explanations. Configure a provider to use an external LLM.':'Only metadata and computed results are sent to the selected provider.'}</p><div className="cq-chat-messages" role="log" aria-live="polite">{!messages.length&&<div className="cq-chat-welcome"><p>Ask about coverage, changes, metadata or technical terms.</p>{['How much vegetation has been lost?','What changed between these images?','What CRS is being used?','What does NDVI mean?'].map(q=><button key={q} onClick={()=>setQuestion(q)}>{q}</button>)}</div>}{messages.map((m,i)=><article key={i} className={'cq-message '+m.role}><span>{m.role==='user'?'You':'SatQuery'}</span><p>{m.content}</p>{m.trace&&<small>{m.trace}</small>}</article>)}{chatBusy&&<p role="status">Reading the evidence…</p>}</div><form onSubmit={submit}><label className="sr-only" htmlFor="evidence-question">Question about imagery</label><textarea id="evidence-question" value={question} onChange={e=>setQuestion(e.target.value)} maxLength={2000} placeholder="Ask about your current imagery…"/><button className="cq-primary" disabled={chatBusy||!!busy||!question.trim()}>Ask <ArrowRight size={15}/></button></form></section>
   {(mode==='single'?['a']:['a','b']).filter(key=>data[key]).map(key=><section key={key} className="cq-card cq-metadata"><h2>{key==='a'?'T1 / Image A':'T2'} metadata & bands</h2><Metadata data={data[key]}/><label>Input category<select value={maps[key].category} disabled={!!busy||chatBusy} onChange={e=>mappingChange(key,'category',e.target.value)}>{['unknown','rgb','multispectral','sar'].map(c=><option key={c}>{c}</option>)}</select></label><p className="cq-caption">Band count alone cannot identify SAR or spectral wavelengths. Confirm category and roles; indices use the scale/offset below, not display colours.</p><div className="cq-band-grid">{['red','green','blue','nir','swir','intensity'].map(role=><label key={role}>{role.toUpperCase()}<select aria-label={`${key} ${role} band`} value={maps[key][role]} disabled={!!busy||chatBusy} onChange={e=>mappingChange(key,role,+e.target.value)}><option value={-1}>Not available</option>{data[key].bands.map((_,i)=><option key={i} value={i}>Band {i+1}</option>)}</select></label>)}{['scale','offset'].map(field=><label key={field}>{field}<input type="number" step="any" value={maps[key][field]} disabled={!!busy||chatBusy} onChange={e=>mappingChange(key,field,+e.target.value)}/></label>)}</div></section>)}
   {!!numericStats.length&&<section className="cq-card cq-metadata"><h2>Raw band statistics · {mode==='bitemporal'?'T2':'T1'}</h2><p className="cq-caption">Finite, non-nodata values on the reduced grid. Histogram bins span each band's min–max.</p>{numericStats.map((s,i)=><details key={i} open={i===0}><summary>Band {i+1} · mean {format(s.mean)}</summary><p>Min {format(s.min)} · Max {format(s.max)} · SD {format(s.std)} · N {s.count.toLocaleString()}</p><div className="cq-histogram" aria-label={`Band ${i+1} histogram`}>{s.histogram.map((v,j)=><span key={j} title={`Bin ${j+1}: ${v} pixels`} style={{height:Math.max(1,v/Math.max(...s.histogram,1)*100)+'%'}}/>)}</div></details>)}</section>}
  </aside></div><p className="cq-footnote">Prototype limits: no automatic image registration, atmospheric correction, scene captioning, advanced SAR classification or validated confidence estimates. Mask coverage is not water depth or elevation.</p></main>
 </div>;
}
function Metadata({data}){const m=data.metadata;return <><dl>{Object.entries({File:m.filename,Dimensions:`${m.width} × ${m.height}`,Bands:m.bands,'Data type':m.dataType,CRS:m.crs,Resolution:m.resolution?m.resolution.join(' × ')+' '+m.units:null,Bounds:m.bounds?.join(', '),Nodata:m.nodata}).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{format(value)}</dd></div>)}</dl><details><summary>Transform and band metadata</summary><pre>{JSON.stringify({transform:m.transform,bands:m.bandInfo},null,2)}</pre></details></>;}

